### ISSUE TITLE
CI failure: linear search algorithm, string array and recursive algorithm.

### ISSUE THREAD

**Issue by dlesnoff** [TheAlgorithms/Nim#31]
Currently, CI fails due to the linear search algorithm.
There is an issue with the recursive algorithm for string arrays.

```nim
proc recursiveLinearSearch*[T](arr: openArray[T], key: T, idx: Nat = arr.low.Nat): OptNat=
  # Recursion is another method for linear search.
  # Recursive calls replace the for loop.

  # `none(Natural)` is returned when the array is traversed completely
  # and no key is matched, or when `arr` is empty.
  if idx > arr.high:
    return none(Natural)
  if arr[idx] == key:
    return some(idx)
  echo idx, " ", arr[idx], " ", key
  recursiveLinearSearch(arr, key, idx + 1)
```
for the test:
```nim
var arr = ["0", "c", "a", "u", "5", "7"]
check recursiveLinearSearch(arr, "5") == some(Natural(4))
```
outputs:
```raw
0  5
1  5
2  5
3  5
4  5
5  5
```
Expected output:
```raw
0 0 5
1 c 5
2 a 5
3 u 5
```
We could maybe fix it by converting the example test array to a sequence:
```raw
var arr = @["0", "c", "a", "u", "5", "7"]
```

**Comment by ZoomRmc** [comment]
Currently the testcase "Search in a string array matching with a string matching value" is failing, returning `None`, due to openArray of `arr` resolving to array of empty strings, inside the recursive search it's `["", "", "", "", "", ""]`.

Changing the `arr` to `const` or to a variable `seq` (instead of array) fixes execution.

I'll try to investigate and post an upstream issue.

**Comment by dlesnoff** [comment]
Thanks for the minimal repro and upstream reports, and sorry for the duplicate issue.
For the linear search script, it felt fine to convert to a variable `seq`. I am uneasy to statically allocate an array of dynamically allocated strings. I did not even thought changing `arr` to `const` to be fair.

Is it due to the default argument depending from another argument?

**Comment by ZoomRmc** [comment]
Yeah, although I'm not sure why it consistently resolves to an array of empty strings.

Using consts with strings or other dynamically allocated types, such as tables, is perfectly fine in Nim. Personally, if it's a literal, it goes into a const, because it's what *literal* is. On the other hand, if all the test cases used consts we wouldn't have found this bug, so it's win-win situation all around!

**Comment by beef331** [comment]
To be fair `arr.low` will always be `0` and an `int`, `openArray[T]` does not keep index information.

**Comment by dlesnoff** [comment]
@beef331 Thanks, I am going to change this.
